// <auto-generated />
namespace AnimeLand.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BookAuthors_BookGenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookAuthors_BookGenres));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281807378_BookAuthors_BookGenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
